/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formatki;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.PersistenceException;
import javax.persistence.TypedQuery;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomek
 */
public class RezerwacjeSzukaj extends javax.swing.JFrame {
     private EntityManagerFactory emf;
     DefaultListModel<kino.Rezerwacja> seansListModel;
     DefaultListModel<kino.Rezerwacja> rezerwacjaListModel;
      
     
      
    /**
     * Creates new form Rezerwacje
     */
    public RezerwacjeSzukaj() {
        initComponents();
        rezerwacjaListModel = new DefaultListModel<>();
        rezerwacjeList.setModel(rezerwacjaListModel);
        
    }
     private EntityManager getEntityManager() {
            if (emf==null) emf=Persistence.createEntityManagerFactory("kinoPU2");
            return emf.createEntityManager();
     }
      private void getRezerwacje()
    {
        String Imie= ImiejTextField.getText();
        String Nazwisko= NazwiskojTextField.getText();
        String Tytul= FilmjTextField.getText();
        
        EntityManager em=getEntityManager();
        TypedQuery<kino.Rezerwacja> q;
        rezerwacjaListModel.clear();
        try {
            q = em.createNamedQuery("Rezerwacja.findByKlientFilm", kino.Rezerwacja.class);
            
            q.setParameter("tytul","%"+Tytul+"%");
            q.setParameter("imie",Imie+"%");
            q.setParameter("nazwisko",Nazwisko+"%");
            
            for(kino.Rezerwacja rezerwacja : q.getResultList())
            {
                rezerwacjaListModel.addElement(rezerwacja);
               
            }
        }
        catch(PersistenceException ex)
        {
            Logger.getLogger(RezerwacjeSzukaj.class.getName()).log(Level.SEVERE, null, ex);
            
            JOptionPane.showMessageDialog(null,"Błąd połączenia z bazą danych");
        }
        finally {
            em.close();
        }
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImiejLabel = new javax.swing.JLabel();
        NazwiskojLabel = new javax.swing.JLabel();
        FilmjLabel = new javax.swing.JLabel();
        ImiejTextField = new javax.swing.JTextField();
        NazwiskojTextField = new javax.swing.JTextField();
        WyszukajjButton = new javax.swing.JButton();
        PrzejdzjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rezerwacjeList = new javax.swing.JList<>();
        FilmjTextField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        zamknijMItem = new javax.swing.JMenuItem();
        zamknijOknoMItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        filmyMItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Szukanie Rezerwacji");

        ImiejLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ImiejLabel.setText("Imię");

        NazwiskojLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NazwiskojLabel.setText("Nazwisko");

        FilmjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FilmjLabel.setText("Film");

        WyszukajjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WyszukajjButton.setText("Wyszukaj Rezerwacje");
        WyszukajjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WyszukajjButtonActionPerformed(evt);
            }
        });

        PrzejdzjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PrzejdzjButton.setText("Przejdz do Rezerwacji");
        PrzejdzjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrzejdzjButtonActionPerformed(evt);
            }
        });

        rezerwacjeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(rezerwacjeList);

        FilmjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilmjTextFieldActionPerformed(evt);
            }
        });

        fileMenu.setText("File");

        zamknijMItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        zamknijMItem.setText("Zamknij Program");
        zamknijMItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknijMItemActionPerformed(evt);
            }
        });
        fileMenu.add(zamknijMItem);

        zamknijOknoMItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        zamknijOknoMItem.setText("Zamknij Okno");
        zamknijOknoMItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknijOknoMItemActionPerformed(evt);
            }
        });
        fileMenu.add(zamknijOknoMItem);

        jMenuBar1.add(fileMenu);

        viewMenu.setText("View");

        filmyMItem.setText("Filmy");
        filmyMItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmyMItemActionPerformed(evt);
            }
        });
        viewMenu.add(filmyMItem);

        jMenuBar1.add(viewMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WyszukajjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NazwiskojLabel)
                            .addComponent(ImiejLabel)
                            .addComponent(FilmjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ImiejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(FilmjTextField)
                            .addComponent(NazwiskojTextField)))
                    .addComponent(PrzejdzjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ImiejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ImiejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NazwiskojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NazwiskojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FilmjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FilmjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(WyszukajjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PrzejdzjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void WyszukajjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WyszukajjButtonActionPerformed
        // TODO add your handling code here:
        getRezerwacje();
    }//GEN-LAST:event_WyszukajjButtonActionPerformed

    private void PrzejdzjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrzejdzjButtonActionPerformed
        // TODO add your handling code here:
         EntityManager em = getEntityManager();
        kino.Rezerwacja rezer = rezerwacjeList.getSelectedValue();
        
        new Rezerwacje(rezer).setVisible(true);
        
    }//GEN-LAST:event_PrzejdzjButtonActionPerformed

    private void FilmjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilmjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FilmjTextFieldActionPerformed

    private void zamknijMItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknijMItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_zamknijMItemActionPerformed

    private void zamknijOknoMItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknijOknoMItemActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_zamknijOknoMItemActionPerformed

    private void filmyMItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmyMItemActionPerformed
        // TODO add your handling code here:
        new Filmy().setVisible(true);
    }//GEN-LAST:event_filmyMItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RezerwacjeSzukaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RezerwacjeSzukaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RezerwacjeSzukaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RezerwacjeSzukaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RezerwacjeSzukaj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FilmjLabel;
    private javax.swing.JTextField FilmjTextField;
    private javax.swing.JLabel ImiejLabel;
    private javax.swing.JTextField ImiejTextField;
    private javax.swing.JLabel NazwiskojLabel;
    private javax.swing.JTextField NazwiskojTextField;
    private javax.swing.JButton PrzejdzjButton;
    private javax.swing.JButton WyszukajjButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem filmyMItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<kino.Rezerwacja> rezerwacjeList;
    private javax.swing.JMenu viewMenu;
    private javax.swing.JMenuItem zamknijMItem;
    private javax.swing.JMenuItem zamknijOknoMItem;
    // End of variables declaration//GEN-END:variables
}
